### ISSUE TITLE
Create a livl-shell logo 

### ISSUE THREAD

**Issue by jvondermarck** [Livl-Corporation/livl-shell#15]
optional but can be good

**Comment by FranckG28** [comment]
![image](https://github.com/Livl-Corporation/livl-shell/assets/19238963/85056f18-135e-45f2-b978-7e539500c4f1)
what do you think ?

**Comment by jvondermarck** [comment]
@FranckG28 Woooaw that is awesome !! We know should put it in our README and also in our index.html page !! Thank you Mister Figma !!
